site_name: PictoPy
repo_name: AOSSIE-Org/PictoPy
repo_url: https://github.com/AOSSIE-Org/PictoPy
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/PictoPy-logo.png
  favicon: assets/PictoPy-logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer
  language: en
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

extra_css:
  - stylesheets/output.css
  - stylesheets/extra.css

nav:
  - GSoC:
      - GSoC: BassamAdnan.md
      

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bassamadnan/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bassam-adnan-a2a287229/
